# -*- coding: utf-8 -*-
"""TItanicData.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1bCGBKSa-j7YnvD0TlJ3Wv9CiJMEnljyB
"""

from google.colab import files
uploaded =files.upload()

import pandas as pd
import numpy as np
import seaborn as sns
import matplotlib.pyplot as plt

data=pd.read_csv('/content/tested.csv')
data.head()

## summary of the   dataset
 data.info()

## discriptive  summary of the datset
data.describe()

data.shape

## List down all the columns names
data.columns

## missing values in the dataset
data.isnull().sum()

## Remove the duplicategs
data[data.duplicated()]

## Remove the duplicates
data.drop_duplicates()

data.shape

data.head()

for column in data.columns:
  sns.histplot(data[column],kde=True)

sns.histplot(data['Ticket'])

# univeriate,bitvariate,multivariate analysis
sns.pairplot(data)

## categorical plot
sns.catplot(x='Fare',y='Ticket',data=data,kind='box')

sns.scatterplot(x='Fare',y='ph',hue='Ticket',data=data())